export const FLIGHT_TUNING = {
  baselineWing: {
    trimAirspeedKmh: 38,
    minControllableAirspeedKmh: 18,
    maxAirspeedKmh: 55,
    baselineSinkMetersPerSecond: 1.02,
    speedToSinkCurveDivisor: 150,
    turnRateMinAirspeedMetersPerSecond: 6,
    flareMinAirspeedKmh: 9,
    bestGlideReferenceKmh: 39,
  },
  controls: {
    speedBarAirspeedGainKmh: 10.5,
    symmetricBrakeAirspeedLossKmh: 12.5,
    deepBrakeAirspeedLossKmh: 5.5,
    responsivenessAirspeedGainKmh: 4,
    brakeToRollDeg: 28,
    weightShiftAuthorityDeg: 12,
    brakeSinkLinearMetersPerSecond: 0.42,
    brakeSinkQuadraticMetersPerSecond: 0.65,
    airspeedResponseRate: 16,
    bankResponseRate: 30,
    coordinationBankResponseGain: 34,
  },
  stability: {
    stallBrakeStart: 0.72,
    stallBrakeRange: 0.24,
    stallAirspeedReferenceKmh: 23,
    stallAirspeedRangeKmh: 8,
    stallAngleOfAttackStartDeg: 13.4,
    stallAngleOfAttackRangeDeg: 5.2,
    speedBarStallRelief: 0.18,
    recoveryAssistStallRelief: 0.65,
    coordinationAuthorityGain: 0.42,
    stallAuthorityPenalty: 0.38,
    controlAuthorityFloor: 0.62,
    controlAuthorityCeiling: 1.16,
    gustRollMagnitudeDeg: 4.4,
    bankLimitDeg: 46,
    loadFactorCosFloor: 0.74,
    inducedTurnSinkMultiplier: 0.95,
    stallTurnRatePenalty: 0.24,
    stallSinkMultiplier: 3.3,
    flareStallPenalty: 0.3,
  },
  liftSources: {
    fallbackRidgeTerrainWindowMeters: 4_500,
    fallbackRidgeWindStartKmh: 8,
    fallbackRidgeWindRangeKmh: 16,
    fallbackRidgeWindCap: 1.35,
    ridgeWindStartKmh: 8,
    ridgeWindRangeKmh: 14,
    ridgeWindCap: 1.45,
    defaultThermalDriftFactor: 0.28,
    thermalCoreRadiusMultiplier: 0.35,
    thermalCoreBaseFraction: 0.7,
    thermalCoreCenteringBonus: 0.3,
    thermalEdgeLiftFraction: 0.72,
    thermalSinkRingRadiusMultiplier: 1.45,
    turbulencePrimaryMix: 0.62,
    turbulenceSecondaryMix: 0.38,
    turbulenceVerticalGustScale: 0.78,
    windGradientSurfaceFactor: 0.58,
    windGradientReferenceHeightMeters: 55,
    windGradientExponent: 0.35,
    surfaceTurbulenceBoost: 0.22,
  },
  phaseModel: {
    launchDurationSeconds: 8,
    approachHeightMeters: 24,
    flareEffectivenessThreshold: 0.1,
    flarePhaseHeightMeters: 10,
    flareArmingHeightMeters: 8,
  },
  landing: {
    flareBrakeStart: 0.58,
    flareBrakeRange: 0.32,
    flareLiftHeightMeters: 5,
    flareLiftMultiplier: 3.4,
    flareDragHeightMeters: 7,
    flareDragMultiplierKmh: 10,
    touchdownHeightMarginMeters: 0.4,
    touchdownVerticalRelief: 0.72,
    touchdownGroundRelief: 0.42,
    verticalSpeedSeverityMultiplier: 2.35,
    groundSpeedSeverityOffsetKmh: 12,
    groundSpeedSeverityDivisor: 5,
    bankSeverityDivisorDeg: 10,
    approachErrorSeverityDivisorDeg: 32,
    landingDistanceSeverityDivisorMeters: 38,
    smoothSeverityThreshold: 2.4,
    firmSeverityThreshold: 3.8,
    hardSeverityThreshold: 5.4,
    groundEffectHeightMeters: 3.8,
    groundEffectLiftMultiplier: 0.42,
    groundEffectSinkRelief: 0.34,
  },
  attitude: {
    trimPitchDeg: -6,
    trimAngleOfAttackDeg: 5.8,
    brakeAngleOfAttackGainDeg: 8.2,
    speedBarAngleOfAttackLossDeg: 4.6,
    flareAngleOfAttackGainDeg: 5.8,
    turbulenceAngleOfAttackGainDeg: 1.2,
    minAngleOfAttackDeg: -4,
    maxAngleOfAttackDeg: 22,
    speedBarPitchGainDeg: 3.8,
    symmetricBrakePitchLossDeg: 8.4,
    stallPitchGainDeg: 8.8,
    flarePitchGainDeg: 6.2,
    turbulencePitchGainDeg: 1.4,
    minPitchDeg: -22,
    maxPitchDeg: 12,
    pitchResponseRate: 40,
  },
} as const

export type FlightTuning = typeof FLIGHT_TUNING
